### ISSUE TITLE
Issue running Entropy on ESP32

### ISSUE THREAD

**Issue by rohanb1965** [pmjdebruijn/Arduino-Entropy-Library#4]
Hi I know this is an old library but I want to move a project running on a mega2560 to esp32 but entropy will not compile I am  guessing its because its not an AVR or a DUE

E:\XXX\libraries\Entropy\Entropy.cpp: In member function 'uint32_t EntropyClass::random()':
E:\XXX\libraries\Entropy\Entropy.cpp:92:16: error: 'ATOMIC_RESTORESTATE' was not declared in this scope
   ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
                ^
E:\XXX\libraries\Entropy\Entropy.cpp:92:35: error: 'ATOMIC_BLOCK' was not declared in this scope
   ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
                                   ^
I have used this library for years and love it 

Any ideas

**Comment by DANYDHSV** [comment]
I need to know how I can enter to sleep mode or powerdown mode at Arduino Mega 2560, this library is amazing but it does not allow me do it.

**Comment by pmjdebruijn** [comment]
I'm not the original author, you might want to look into:

https://code.google.com/archive/p/avr-hardware-random-number-generation/
